### ISSUE TITLE
<http://www.w3.org/2003/01/geo/wgs84_pos#> support

### ISSUE THREAD

**Issue by erfgoed-en-locatie** [erfgoed-en-locatie/sparql-geojson#1]
Version 0.1 only supports datatype http://www.opengis.net/ont/geosparql#wktLiteral from SPARQL, but most point data is encoded as http://www.w3.org/2003/01/geo/wgs84_pos# (geonames for example).

**Comment by jobspierings** [comment]
Tool curently not in use in project.
